#%RAML 1.0 DataType


type: object
properties:
  customer:
    type: string
    example: "profile47064541"
  action:
    type: string
    example: "credit_debit"
  data: 
    type: !include credit-debit-data-type.raml