#%RAML 1.0 DataType

type: object
properties:
  transaction_id:
    type: string
    example: "s12707690010"
  amount:
    type: integer
    example: 40
  note:
    type: string
    example: "adjusted"
