#%RAML 1.0 DataType

type: object
properties:
  id:
    type: string
    example:  "profile47064541"
  created_at:
    type: integer
    example:  1625154655
  email:
    type: string
    example:  "rajaramcoke@gmail.com"
  first_name:
    type: string
    example:  "Rajaram"
  last_name:
    type: string
    example:  "Pasupathy"
  status:
    type: string
    example:  "active"
  score:
    type: integer
    example:  0
  spent:
    type: integer
    example:  0
  pending:
    type: integer
    example:  0
  image_url:
    type: nil
    example:  null
  events:
    type: array
    example:  []
  