#%RAML 1.0 DataType

type: object
properties:
  transaction_id:
    type: string
    example: "s12707450100"
  total:
    type: number
    example: 93.8
  product_id:
    type: string
    example: "cis11628000020"
  product_name:
    type: string
    example: "185321 Acetate Full-Rim Frame"
  product_url:
    type: string
    example: "https://static.zennioptical.com/production/products/general/18/53/185321-eyeglasses-front-view.jpg?resize=1200px:*&output-quality=90"
  quantity:
    type: integer
    example: 2
  points_rewarded:
    type: integer
    example: 0
  subtotal:
    type: number
    example: 93.8
  price:
    type: number
    example: 46.9