#%RAML 1.0 DataType

type: object
properties:
  id:
    type: string
    example: "s12707450100"
  status:
    type: string
    example: "accepted"
  event:
    type: string
    example: "60ddea455ceab0fb4b000007"
  created_at:
    type: string
    example: "2021-07-01T09:16:05-07:00"
  updated_at:
    type: string
    example: "2021-07-01T09:16:05-07:00"
  total:
    type: number
    example: 93.8
  items:
    type: array
    items: !include items-data-type.raml