#%RAML 1.0 DataType

type: object
properties:
  id:
    type: string
    example: "test_account1"
  created_at:
    type: integer
    example: 1615235020
  email:
    type: string
    example: "testaccount1@gmail.com"
  first_name:
    type: string
    
    example: "RajaramTest"
  last_name:
    type: string
    example: "PasupathyTest"
  status:
    type: string
    example: "active"
  score:
    type: integer
    example: 0
  spent:
    type: integer
    example: 0
  pending:
    type: integer
    example: 0
  image_url:
    type: string | nil
    example: null
  events:
    type: array
    example: []