#%RAML 1.0 DataType

type: object
properties:
  id:
    type: string
    example: "60fb4f281c3bfd8c1f000019"
  action:
    type: string
    example: "daily_login"
  label:
    type: string
    example: "Daily login"
  points:
    type: integer
    example: 0
  timestamp:
    type: string
    example: "2021-07-23T16:22:16-07:00"
  properties:
    type: array
    example: []

