#%RAML 1.0 DataType

type: object
properties:
  id:
    type: string
    example: "ramtest1"
  optin_at:
    type: integer
    example: 1607458546
  last_login_at:
    type: string | nil
    example: null
  updated_at:
    type: integer
    example: 1607458546
  first_name:
    type: string
    example: "Rajaram"
  last_name:
    type: string
    example: "Pasupathy"
  email:
    type: string
    example: "rajaram@zenni.com"
  birth_date:
    type: string | nil
    example: null
  gender:
    type: string | nil
    example: null
  language:
    type: string |  nil
    example: null
  nickname:
    type: string | nil
    example: null
  status:
    type: string
    example: "active"
  score:
    type: integer
    example: 0
  spent:
    type: integer
    example: 0
  reserved:
    type: integer
    example: 0
  spendable:
    type: integer
    example: 0
  pending:
    type: integer
    example: 0
  properties:
    type: string | nil
    example: null
  purchase_total:
    type: integer
    example: 250
  purchase_count:
    type: integer
    example: 3
  purchase_last_date:
    type: string
    example: "2020-12-08"
