#%RAML 1.0
title: ANTAVO-API
version: 1.0


traits:
  header-details:
    headers:
      Authorization:
        required: true
        type: string
      client_id:
        required: true
        type: string 
      client_secret:
        required: true
        type: string 
      profile_id:
        required: true
        type: string
types:
  usersResponse : !include types/user-response.raml
  multipleRewardsCliamRequest : !include types/multiple-reward-cliam-request.raml
  multipleRewardsCliamResponse : !include types/multiple-reward-cliam-response.raml
  creditDebitAdjustmentsResponse: !include types/credit-debit-adjustments-response.raml
  usersOptInRequest: !include types/users-opt-in-request.raml
  usersOptInResponse: !include types/users-opt-in-respnse.raml
  usersOptOutRequest: !include types/users-opt-out-request.raml
  usersOptOutResponse: !include types/users-opt-out-response.raml 
  usersCheckoutRequest: !include types/users-checkout-request.raml
  usersCheckoutResponse: !include types/users-checkout-respnse.raml
  usersClaimRewardsResponse: !include types/users-claim-rewards-response.raml
  usersRewardsResponse: !include types/users-rewards-response.raml
  updateUserRequest: !include types/update-user-request.raml
  updateUserResponse: !include types/update-user-response.raml
  creditDebitAdjustmentsRequest: !include types/credit-debit-adjustments-request.raml
  usersTransactionsResponse: !include types/users-transactions-response.raml
  
  usersEventsResponse: !include types/users-events-response.raml

/users/{customerId}:
  get:
    is:
      header-details:
    description: This endpoint for get user details.
    responses:
      200:
        body:
          application/json:
            type: usersResponse
            example:
              !include /examples/usersResponse.json

/users/optIn:
  post:
    is:
      header-details:
    description: This endpoint for user optIn.
    body:
      application/json:
           type: usersOptInRequest
           example:
             !include /examples/usersOptInRequest.json
    responses:
      200:
        body:
          application/json:
            type: usersOptInResponse
            example:
              !include /examples/usersOptInResponse.json

/users/optOut:
  post:
    is:
      header-details:
    description: This endpoint for user optOut.
    body:
      application/json:
          type: usersOptOutRequest
          example:
            !include /examples/usersOptOutRequest.json
    responses:
      200:
        body:
          application/json:
            type: usersOptOutResponse
            example:
              !include /examples/usersOptOutResponse.json

/users/checkout:
  post:
    is:
      header-details:
    description: This endpoint for create order.
    body:
      application/json:
        type: usersCheckoutRequest
        example:
         !include /examples/usersCheckoutRequest.json
    responses:
      200:
        body:
         application/json:
            type: usersCheckoutResponse
            example:
             !include /examples/usersCheckoutResponse.json

/users/profile:
  post:
    is:
      header-details:
    description: This endpoint for update user.
    body:
      application/json:
        type: updateUserRequest
        example:
         !include /examples/updateUserRequest.json
    responses:
      200:
        body:
         application/json:
            type: updateUserResponse
            example:
             !include /examples/updateUserResponse.json

/users/{customerId}/rewards:
  get:
    is:
      header-details:
    description: This endpoint for get user reward details.
    responses:
      200:
        body:
          application/json:
            type: usersRewardsResponse[]
            example:
              !include /examples/usersRewardsResponse.json
  /claim:
    post:
      is:
        header-details:
      description: This endpoint for multiple rewards claims
      body:
        application/json:
          type: multipleRewardsCliamRequest
          example:
           !include /examples/multipleRewardsClaimRequest.json
      responses:
        200:
          body:
            application/json:
              type: multipleRewardsCliamResponse
              example:
               !include /examples/multipleRewardsClaimResponse.json

  /{rewardId}:
    post:
      is:
        header-details:
      description: This endpoint for create claim.
      responses:
         200:
           body:
             application/json:
               type: usersClaimRewardsResponse
               example:
                 !include /examples/usersClaimRewardsResponse.json

/users/{CustomerId}/events:
  get:
    is:
      header-details:
    queryParameters:
      limit:
        type: integer
        required: false
        example: 10
      offset:
        type: integer
        required: false
        example: 2
    description: This endpoint for get user event details.
    responses:
      200:
        body:
          application/json:
            type: usersEventsResponse
            example:
              !include /examples/usersEventsResponse.json

/users/{CustomerId}/transactions:
  get:
    is:
      header-details:
    queryParameters:
      limit:
        type: integer
        required: false
        example: 10
      offset:
        type: integer
        required: false
        example: 2
    description: This endpoint for get user transactions details.
    responses:
      200:
        body:
          application/json:
            type: usersTransactionsResponse
            example:
              !include /examples/usersTransactionsResponse.json

/users/creditDebitAdjustments:
  post:
    is:
      header-details:
    description: This endpoint for create credit and debit adjustments.
    body:
      application/json:
        type: creditDebitAdjustmentsRequest
        example:
         !include /examples/creditDebitAdjustmentsRequest.json
    responses:
      200:
        body:
         application/json:
            type: creditDebitAdjustmentsResponse
            example:
             !include /examples/creditDebitAdjustmentsResponse.json  